//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 04:06:01 PM SAMT 
//


package ivan.vatlin.soap.car_specification;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_ivan_vatlin.car_specification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_ivan_vatlin.car_specification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link CarSpecificationDetailsRequest }
     * 
     */
    public CarSpecificationDetailsRequest createCarSpecificationDetailsRequest() {
        return new CarSpecificationDetailsRequest();
    }

    /**
     * Create an instance of {@link CarSpecificationDetailsResponse }
     * 
     */
    public CarSpecificationDetailsResponse createCarSpecificationDetailsResponse() {
        return new CarSpecificationDetailsResponse();
    }

    /**
     * Create an instance of {@link CarSpecification }
     * 
     */
    public CarSpecification createCarSpecification() {
        return new CarSpecification();
    }

}
