//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 04:06:01 PM SAMT 
//


package ivan.vatlin.soap.car_specification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchBy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="searchBy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="brand"/>
 *     &lt;enumeration value="model"/>
 *     &lt;enumeration value="yearMade"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "searchBy")
@XmlEnum
public enum SearchBy {

    @XmlEnumValue("brand")
    BRAND("brand"),
    @XmlEnumValue("model")
    MODEL("model"),
    @XmlEnumValue("yearMade")
    YEAR_MADE("yearMade");
    private final String value;

    SearchBy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SearchBy fromValue(String v) {
        for (SearchBy c: SearchBy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
