//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 03:38:42 PM SAMT 
//


package ivan.vatlin.soap.cars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Car complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Car">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="carSpecification" type="{https://www.ivan.vatlin/cars}carSpecification"/>
 *         &lt;element name="pricePerDay" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="registrationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carStatus" type="{https://www.ivan.vatlin/cars}carStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Car", propOrder = {
    "id",
    "carSpecification",
    "pricePerDay",
    "registrationNumber",
    "carStatus"
})
public class Car {

    protected long id;
    @XmlElement(required = true)
    protected CarSpecification carSpecification;
    protected double pricePerDay;
    @XmlElement(required = true)
    protected String registrationNumber;
    protected CarStatus carStatus;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the carSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link CarSpecification }
     *     
     */
    public CarSpecification getCarSpecification() {
        return carSpecification;
    }

    /**
     * Sets the value of the carSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarSpecification }
     *     
     */
    public void setCarSpecification(CarSpecification value) {
        this.carSpecification = value;
    }

    /**
     * Gets the value of the pricePerDay property.
     * 
     */
    public double getPricePerDay() {
        return pricePerDay;
    }

    /**
     * Sets the value of the pricePerDay property.
     * 
     */
    public void setPricePerDay(double value) {
        this.pricePerDay = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the carStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CarStatus }
     *     
     */
    public CarStatus getCarStatus() {
        return carStatus;
    }

    /**
     * Sets the value of the carStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarStatus }
     *     
     */
    public void setCarStatus(CarStatus value) {
        this.carStatus = value;
    }

}
