//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 03:38:42 PM SAMT 
//


package ivan.vatlin.soap.cars;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{https://www.ivan.vatlin/cars}search"/>
 *         &lt;element name="all" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "search",
        "all"
})
@XmlRootElement(name = "CarDetailsRequest", namespace = "https://www.ivan.vatlin/cars")
public class CarDetailsRequest {

    protected Search search;
    protected String all = "";

    /**
     * Gets the value of the search property.
     *
     * @return possible object is
     * {@link Search }
     */
    public Search getSearch() {
        return search;
    }

    /**
     * Sets the value of the search property.
     *
     * @param value allowed object is
     *              {@link Search }
     */
    public void setSearch(Search value) {
        this.search = value;
    }

    /**
     * Gets the value of the all property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAll() {
        return all;
    }

    /**
     * Sets the value of the all property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAll(String value) {
        this.all = value;
    }

}
