//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 03:38:42 PM SAMT 
//


package ivan.vatlin.soap.cars;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for carStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="carStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IDLE"/>
 *     &lt;enumeration value="IN_USE"/>
 *     &lt;enumeration value="IN_MAINTAINANCE"/>
 *     &lt;enumeration value="WRITTEN_OFF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "carStatus")
@XmlEnum
public enum CarStatus {

    IDLE,
    IN_USE,
    IN_MAINTAINANCE,
    WRITTEN_OFF;

    public String value() {
        return name();
    }

    public static CarStatus fromValue(String v) {
        return valueOf(v);
    }

}
