//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.13 at 03:38:42 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.ivan.vatlin/cars", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ivan.vatlin.soap.cars;
